---
Name: modular-social-routes
---
Director:
  rules:
    'member': Modular\Controllers\SocialMember_Controller
    'organisation': Modular\Controllers\SocialOrganisation_Controller
    'forum': Modular\Controllers\SocialForum_Controller
    'forumtopic': Modular\Controllers\SocialForumTopic_Controller
    'post': Modular\Controllers\SocialPost_Controller
