---
Name: modular-social-routes
---
Director:
  rules:
    'member': Modular\Controllers\Social\MemberController
    'organisation': Modular\Controllers\Social\OrganisationController
    'forum': Modular\Controllers\Social\ForumController
    'forumtopic': Modular\Controllers\Social\ForumTopicController
    'post': Modular\Controllers\Social\PostController
